hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.model_dir}/${exp_name}/single
  sweep:
    dir: ${dir.model_dir}/${exp_name}
    subdir: run${hydra.job.num}
  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback

defaults:
  - _self_
  - dir: local
  - model: ffn_model
  - optimizer: adamw
  - scheduler: cosine_with_restart_warmup

output_dir: ~
dataset_name: ~
exp_name: dummy
stage: train
num_train_files: ~
batch_size: 512
seed: 42
benchmark: False
logger: False

trainer:
  max_epochs: 5
  min_epochs: 200
  enable_progress_bar: True
  accelerator: auto
  precision: "16-mixed"
  # precision: 32
  # precision: 64
  gradient_clip_val: ~
  accumulate_grad_batches: 1
  devices: [1]
  val_check_interval: 0.25

early_stopping:
  monitor: "val_r2"
  mode: "max"
  patience: 5

model_checkpoint:
  save_weights_only: True
  monitor: "val_r2"
  mode: "max"
  dirpath: True
  save_top_k: 1
  verbose: 1

used_input_cols:
used_output_cols:
unused_input_cols:
unused_output_cols:
  - ptend_q0002_12
  - ptend_q0002_13
  - ptend_q0002_14
  - ptend_q0002_15
  - ptend_q0002_16
  - ptend_q0002_17
  - ptend_q0002_18
  - ptend_q0002_19
  - ptend_q0002_20
  - ptend_q0002_21
  - ptend_q0002_22
  - ptend_q0002_23
  - ptend_q0002_24
  - ptend_q0002_25
  - ptend_q0002_26

ignore_mask: True
