hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.model_dir}/${exp_name}/${dir_name}
  sweep:
    dir: ${dir.model_dir}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: ffn_model
  - optimizer: adam
  - scheduler: cosine_with_restart_warmup

dir_name: single
exp_name: dummy
stage: train
num_train_files: ~
batch_size: 4096
seed: 42
benchmark: False
logger: False

trainer:
  max_epochs: 20
  min_epochs: 100
  enable_progress_bar: True
  accelerator: auto
  precision: "16-mixed"
  # precision: 64
  gradient_clip_val: ~
  accumulate_grad_batches: 1
  devices: [1]

early_stopping:
  monitor: "val_r2"
  mode: "max"
  patience: 5

model_checkpoint:
  save_weights_only: True
  monitor: "val_r2"
  mode: "max"
  dirpath: True
  save_top_k: 1
  verbose: 1

used_input_cols:
  # - state_t
  # - state_q0001
  # - state_q0002
  # - state_q0003
  # - state_u
  # - state_v
  # - state_ps
  # - pbuf_LHFLX
  # - pbuf_SHFLX
  # - cam_in_LWUP
used_output_cols:
  # - ptend_t
unused_input_cols:
unused_output_cols:
